const leaderboardData = {
  overall: [
    { name: "Alex Chen", points: 2850, wins: 45, games: 52, subject: "mixed" },
    { name: "Sarah Johnson", points: 2720, wins: 42, games: 50, subject: "mixed" },
    { name: "Marcus Williams", points: 2590, wins: 38, games: 48, subject: "mixed" },
    { name: "Emma Davis", points: 2480, wins: 35, games: 45, subject: "mixed" },
    { name: "Jamal Brown", points: 2350, wins: 32, games: 42, subject: "mixed" },
    { name: "Lisa Rodriguez", points: 2240, wins: 29, games: 40, subject: "mixed" },
    { name: "David Kim", points: 2180, wins: 27, games: 38, subject: "mixed" },
    { name: "Jessica Taylor", points: 2050, wins: 24, games: 35, subject: "mixed" },
    { name: "Michael Anderson", points: 1980, wins: 22, games: 33, subject: "mixed" },
    { name: "Sophia Martinez", points: 1890, wins: 20, games: 31, subject: "mixed" },
  ],
  math: [
    { name: "Alex Chen", points: 950, wins: 18, games: 20, subject: "math" },
    { name: "Marcus Williams", points: 880, wins: 16, games: 19, subject: "math" },
    { name: "David Kim", points: 820, wins: 14, games: 17, subject: "math" },
    { name: "James Wilson", points: 760, wins: 12, games: 16, subject: "math" },
    { name: "Rachel Green", points: 700, wins: 10, games: 14, subject: "math" },
  ],
  science: [
    { name: "Sarah Johnson", points: 920, wins: 17, games: 19, subject: "science" },
    { name: "Emma Davis", points: 850, wins: 15, games: 18, subject: "science" },
    { name: "Lisa Rodriguez", points: 780, wins: 13, games: 16, subject: "science" },
    { name: "Nina Patel", points: 720, wins: 11, games: 15, subject: "science" },
    { name: "Oliver Chen", points: 680, wins: 9, games: 13, subject: "science" },
  ],
  history: [
    { name: "Jamal Brown", points: 880, wins: 16, games: 18, subject: "history" },
    { name: "Jessica Taylor", points: 810, wins: 14, games: 17, subject: "history" },
    { name: "Thomas Jackson", points: 750, wins: 12, games: 16, subject: "history" },
    { name: "Victoria Lee", points: 690, wins: 10, games: 15, subject: "history" },
  ],
  english: [
    { name: "Emma Davis", points: 850, wins: 15, games: 18, subject: "english" },
    { name: "Charlotte White", points: 800, wins: 13, games: 16, subject: "english" },
    { name: "Benjamin Parker", points: 730, wins: 11, games: 14, subject: "english" },
    { name: "Grace Miller", points: 680, wins: 9, games: 13, subject: "english" },
  ],
  biology: [
    { name: "Sarah Johnson", points: 900, wins: 17, games: 19, subject: "biology" },
    { name: "Emma Davis", points: 820, wins: 14, games: 17, subject: "biology" },
    { name: "Nathan Scott", points: 760, wins: 12, games: 16, subject: "biology" },
    { name: "Sophia Chen", points: 710, wins: 10, games: 15, subject: "biology" },
  ],
};
