const questionBank = {
  math: [
    { q: "What is 15 × 12?", opts: ["150", "180", "200", "220"], ans: 1 },
    { q: "Solve: 2x + 5 = 17", opts: ["x = 4", "x = 5", "x = 6", "x = 11"], ans: 2 },
    { q: "What is 25% of 80?", opts: ["15", "20", "25", "30"], ans: 1 },
    { q: "12² = ?", opts: ["120", "132", "144", "156"], ans: 2 },
    { q: "√144 = ?", opts: ["10", "11", "12", "13"], ans: 2 },
    { q: "What is the sum of angles in a triangle?", opts: ["90°", "180°", "270°", "360°"], ans: 1 },
    { q: "What is 7³?", opts: ["343", "300", "310", "350"], ans: 0 },
    { q: "Solve: 3x - 10 = 20", opts: ["x = 10", "x = 5", "x = 8", "x = 15"], ans: 0 },
    { q: "What is 50% of 200?", opts: ["80", "100", "120", "150"], ans: 1 },
    { q: "What is the LCM of 12 and 18?", opts: ["24", "36", "48", "60"], ans: 1 },
  ],
  science: [
    { q: "What is the chemical symbol for Gold?", opts: ["Go", "Gd", "Au", "Ag"], ans: 2 },
    { q: "What is the speed of light?", opts: ["300,000 km/s", "150,000 km/s", "450,000 km/s", "100,000 km/s"], ans: 0 },
    { q: "How many bones are in the human body?", opts: ["186", "206", "226", "246"], ans: 1 },
    { q: "What is H₂O?", opts: ["Hydrogen peroxide", "Water", "Salt", "Acid"], ans: 1 },
    { q: "What planet is closest to the Sun?", opts: ["Venus", "Mercury", "Mars", "Earth"], ans: 1 },
    { q: "What is the powerhouse of the cell?", opts: ["Nucleus", "Mitochondria", "Ribosome", "Chloroplast"], ans: 1 },
    { q: "What does DNA stand for?", opts: ["Deoxyribonucleic Acid", "Dynamic Nuclear Acid", "Deoxyribose Nucleic Arrangement", "Digital Nucleic Archive"], ans: 0 },
    { q: "What is the boiling point of water?", opts: ["90°C", "100°C", "110°C", "120°C"], ans: 1 },
  ],
  history: [
    { q: "In what year did World War II end?", opts: ["1943", "1944", "1945", "1946"], ans: 2 },
    { q: "Who was the first President of the USA?", opts: ["Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"], ans: 1 },
    { q: "When did the Titanic sink?", opts: ["1910", "1912", "1915", "1920"], ans: 1 },
    { q: "In what year did Columbus reach the Americas?", opts: ["1490", "1491", "1492", "1493"], ans: 2 },
    { q: "Who was the first emperor of Rome?", opts: ["Julius Caesar", "Augustus", "Nero", "Tiberius"], ans: 1 },
  ],
  english: [
    { q: "Which of these is a noun?", opts: ["Run", "Beautiful", "Happy", "Book"], ans: 3 },
    { q: "What is the past tense of 'go'?", opts: ["Goed", "Went", "Going", "Goes"], ans: 1 },
    { q: "Which word is a verb?", opts: ["Happy", "Jump", "Beautiful", "Blue"], ans: 1 },
    { q: "What does 'eloquent' mean?", opts: ["Boring", "Silent", "Fluent and persuasive in speech", "Angry"], ans: 2 },
  ],
  biology: [
    { q: "What is the powerhouse of the cell?", opts: ["Nucleus", "Mitochondria", "Ribosome", "Chloroplast"], ans: 1 },
    { q: "How many chambers does a human heart have?", opts: ["2", "3", "4", "5"], ans: 2 },
    { q: "What is photosynthesis?", opts: ["Cell division", "Energy from sunlight", "Protein synthesis", "DNA replication"], ans: 1 },
    { q: "What do plants need for photosynthesis?", opts: ["Water and oxygen", "Carbon dioxide and sunlight", "Nitrogen and heat", "Sugar and salt"], ans: 1 },
    { q: "What are the basic units of life?", opts: ["Atoms", "Molecules", "Cells", "Tissues"], ans: 2 },
  ],
};
